name: CI

on:
  push:
    branches: [ master ]


jobs:
  vm:
    runs-on: ubuntu-latest

    steps:
      - run: bash pkg_automation.bash -y
        name: Run on Runner ubuntu-latest
    
  container:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8.4-rc1
    steps:
      - run: bash pkg_automation.bash -y
        name: Run on Docker 
        
        
