---
name: Debian 12

on:
  push:
    branches: [ master ]
    paths:
    - 'pkg-deb12/**'
    - 'pkg_automation.bash'
    - 'functions'
    - '.github/workflows/debian12.yml'

  pull_request:
    branches: [ master ]


jobs:

  Debian12:
    runs-on: ubuntu-latest
    container: amd64/debian:bookworm-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Debian 12 
        run: |
          apt update -y
          apt install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

