---
name: Debian 13 - Trixie

on:
  push:
    branches: [ master ]
    paths:
    - 'pkg-deb13/**'
    - 'pkg_automation.bash'
    - 'functions'
    - '.github/workflows/debian13.yml'

  pull_request:
    branches: [ master ]


jobs:

  Debian13:
    runs-on: ubuntu-latest
    container: amd64/debian:trixie-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Debian 13 
        run: |
          apt update -y
          apt install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

