---
name: Linux Build

on:
  push:
    branches: [ master ]
    paths:
    - 'pkg_automation.bash'
    - 'functions'
    - '.github/workflow/linux.yml'

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on Ubuntu
        run: |
          bash pkg_automation.bash -y

  Rocky8:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on Rocky 8 Docker
        run: |
          dnf install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

  Alma8:
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on Alma 8 Docker
        run: |
          dnf update -y
          dnf install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

  Debian10:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on Debian 10 Docker
        run: |
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          apt update && apt install -y sudo
          bash pkg_automation.bash -y

  Debian11:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on Debian 11 Docker
        run: |
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          apt update -y && apt install -y sudo
          bash pkg_automation.bash -y

  CentOS7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on CentOS 7 Docker
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
          yum install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

