---
name: Linux Build

on:
  push:
    branches: [master]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Ubuntu
        run: |
          bash pkg_automation.bash -y

  Rocky8:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Rocky 8 Docker
        run: |
          dnf install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

  Alma8:
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Alma 8 Docker
        run: |
          dnf update -y
          dnf install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

  Debian11:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Debian 11 Docker
        run: |
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          apt update -y && apt install -y sudo
          bash pkg_automation.bash -y

