---
name: macOS build

on:
  push:
    branches:
      - 'master'
      - 'macos'

jobs:
  macOS11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew install git curl make bash
          bash pkg_automation.bash -y
