---
name: macOS build

on:
  push:
    branches:
      - 'master'
      - 'macos'
    paths:
    - 'pkg-macos11/**'
    - 'pkg_automation.bash'
    - 'functions'
    - '.github/workflows/macos.yml'

jobs:
  macOS13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew install git curl make bash
          bash pkg_automation.bash -y
