name: CI

on:
  push:
    branches: [ master ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: bash pkg_automation.bash -y
        name: Run on Runner ubuntu-latest
    
  Rocky8:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8.4-rc1
    steps:
      - uses: actions/checkout@v2
      - run: |
          dnf install -y sudo 
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y
        name: Test on Rocky Docker

  Debian10:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - uses: actions/checkout@v2
      - run: |
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          apt update && apt install -y sudo
          bash pkg_automation.bash -y
        name: Test on Debian10 Docker


  Debian11:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v2
      - run: |
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          apt update -y && apt install -y sudo
          bash pkg_automation.bash -y
        name: Test on Debian11 Docker




  CentOS7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
      - run: |
          yum install -y sudo 
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y
        name: Test on CentOS7 Docker

  CentOS8:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v2
      - run: |
          dnf install -y sudo 
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y
        name: Test on CentOS8 Docker
 
