name: CI

on:
  push:
    branches: [ master ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: bash pkg_automation.bash -y
        name: Run on Runner ubuntu-latest
    
  Rocky:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8.4-rc1
    steps:
      - uses: actions/checkout@v2
      - run: |
          dnf install -y sudo 
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y
        name: Run on Docker
      
