---
name: Ubuntu 22 LTS

on:
  push:
    branches: [ master ]
    paths:
    - 'pkg-ubu22/**'
    - 'pkg_automation.bash'
    - 'functions'
    - '.github/workflows/ubuntu22.yml'

  pull_request:
    branches: [ master ]


jobs:

  Ubuntu 22.04:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test on Ubuntu 22.04 LTS
        run: |
          apt update -y
          apt install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          bash pkg_automation.bash -y

