---
name: Ubuntu Latest

on:
  push:
    branches: [ master ]
    paths:
    - 'pkg-ubu24/**'
    - 'pkg_automation.bash'
    - 'functions'
    - '.github/workflows/ubuntu-latest.yml'

  pull_request:
    branches: [ master ]


jobs:

  UbuntuLatest:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test on Ubuntu Latest
        run: |
          apt update -y
          apt install -y sudo
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          ln -snf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
          printf "%s\n" "America/Los_Angeles" > /etc/timezone
          bash pkg_automation.bash -y

